### ISSUE TITLE
not and issue, question about ide / editor

### ISSUE THREAD

**Issue by ssshake** [cliffordcarnmo/c64-devkit#2]
thanks for putting this together i am just getting started with assembly on my c64.

I would like to know what editor I should be using with this and how to make use of the simulator. I have been using c64 studio up til this point and I'm not sure how to get that sort of feature set with what you have provided here, thanks.

**Comment by cliffordcarnmo** [comment]
Hello and thanks for you question.

There are a plethora of text editors out there and several projects that incorporate editor, debugger and emulator in the same IDE-style package. Personally, I prefer using vim in a UNIX-style terminal and build my projects by using a makefile.

If vim is your cup of tea, check out my config at: https://github.com/cliffordcarnmo/vim-config.

Also, check out Visual Studio Code and Sublime Text if  you are more into that kind of stuff.
